### ISSUE TITLE
Update doesn't work

### ISSUE THREAD

**Issue by equeim** [flathub/com.jetbrains.IntelliJ-IDEA-Community#200]
`flatpak update` show following error:

```
Warning: While pulling runtime/com.jetbrains.IntelliJ_IDEA_Community.Locale/x86_64/stable from remote flathub: Update is older than current version
Error: While pulling app/com.jetbrains.IntelliJ-IDEA-Community/x86_64/stable from remote flathub: Update is older than current version
Updates complete.
error: There were one or more errors
```

`flatpak info com.jetbrains.IntelliJ-IDEA-Community` output is:

```
IntelliJ IDEA Community - Leading Java and Kotlin editor

          ID: com.jetbrains.IntelliJ-IDEA-Community
         Ref: app/com.jetbrains.IntelliJ-IDEA-Community/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 2024.3.1
     License: Apache-2.0
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 1,6 MB
     Runtime: org.freedesktop.Sdk/x86_64/24.08
         Sdk: org.freedesktop.Sdk/x86_64/24.08

      Commit: 8a0b058cab299a4c8dcbd1a47aeecfee74c8afa2f65b711c3eb48bf36996b4fe
      Parent: c7eacda3da014a009b3f6e2f3a145f42ad81c9fc3fa420bf9277bff17486115b
     Subject: new screenshot links (ed214175)
        Date: 2024-12-12 18:03:27 +0000
```

`flatpak remote-info --log flathub com.jetbrains.IntelliJ-IDEA-Community` output is:

```
IntelliJ IDEA Community - The Leading Java and Kotlin IDE

        ID: com.jetbrains.IntelliJ-IDEA-Community
       Ref: app/com.jetbrains.IntelliJ-IDEA-Community/x86_64/stable
      Arch: x86_64
    Branch: stable
   Version: 2024.3.1
   License: Apache-2.0
Collection: org.flathub.Stable
  Download: 2,5 MB
 Installed: 2,9 MB
   Runtime: org.freedesktop.Sdk/x86_64/24.08
       Sdk: org.freedesktop.Sdk/x86_64/24.08

    Commit: 5057e39fae89354a115000b31dae2f64a9a695f7f9d419bd2944442c6882f350
    Parent: 8a0b058cab299a4c8dcbd1a47aeecfee74c8afa2f65b711c3eb48bf36996b4fe
   Subject: new screenshots (#198) (709af613)
      Date: 2024-12-12 17:28:47 +0000
   History: 

    Commit: 8a0b058cab299a4c8dcbd1a47aeecfee74c8afa2f65b711c3eb48bf36996b4fe
   Subject: new screenshot links (ed214175)
      Date: 2024-12-12 18:03:27 +0000

    Commit: c7eacda3da014a009b3f6e2f3a145f42ad81c9fc3fa420bf9277bff17486115b
   Subject: idea: Update ideaIC.tar.gz to 2024.3.1 (#197) (3d84500a)
      Date: 2024-12-09 17:40:55 +0000

    Commit: f37ef4b9a0e7e258df306fc8e759f1b78be662c32fed4c1a8ee66fbc6e8100e9
   Subject: update first run info (fc60dcb4)
      Date: 2024-12-03 21:00:42 +0000

    Commit: 6d39bed165436126bf5dd6b03d1bf2e7e8455e556dde18f34c7ad5d2b4a47bac
   Subject: use local svg (1c15cb47)
      Date: 2024-11-26 09:37:29 +0000

    Commit: 124a2c9431adf7bfbc7c1f8c50d2914332d529ab9fa7a8398461a6d8427e4b38
   Subject: Update Git LFS module to version 3.6.0 (232c52d4)
      Date: 2024-11-21 13:01:27 +0000

    Commit: 8210c165dc5bd38ebcb886f7c8157b0dbf7f8bc4c16fcf0585984fe3f45546d3
   Subject: Update IntelliJ IDEA to version 2024.3 (e58f4bcc)
      Date: 2024-11-13 15:24:31 +0000

    Commit: 29ec3bc9c3d75547c3cafc233cd791a190a7e0fe67b990b3e5157962cc2ba809
   Subject: Update IntelliJ IDEA to version 2024.2.4 (b2535e96)
      Date: 2024-10-23 15:24:35 +0000

    Commit: 81c50190a7b45d3a431bd3fa6fd710498a8d9917f07bf9835d2d57bdaeb357b3
   Subject: Switch IDE to make use of the native launcher for better experience (42e4257d)
      Date: 2024-10-10 20:55:33 +0000

    Commit: 8f285c564a727fe6ce757c7413509890a19f9923a347a063d76357fc7b955d56
   Subject: Update the StartupWMClass in the desktop icon file to match the new application class (b11ee3f9)
      Date: 2024-09-27 14:20:37 +0000

    Commit: 68caa14758c675c8711b98df8bedbb5c30f0954b263153c6601811bef70ee563
   Subject: Allow application to talk to the GPG agent (6f081bc4)
      Date: 2024-09-26 01:00:02 +0000

    Commit: bec0775c99f28a2b1d9826303da602ba3c41f05acee9104bcb3a7e6ad2562cd8
   Subject: idea: Update ideaIC.tar.gz to 2024.2.2 (#179) (b76ef8d9)
      Date: 2024-09-20 01:35:07 +0000

    Commit: 937f53fd7a05474b172e77c24eb8eb465cddb62b01057ef0bc43d46160af3a37
   Subject: Update IntelliJ IDEA to version 2024.2.1 (e5b2a961)
      Date: 2024-08-30 13:19:53 +0000

    Commit: b5714b6c8da43722ceea1a57f2aa2aa3fc8debdc1bd896ad131fcea2def4dc9d
   Subject: idea: Update ideaIC.tar.gz to 2024.2.0.2 (#175) (e46f5ab1)
      Date: 2024-08-23 17:58:12 +0000

    Commit: 3b00c9c3b3bb55b760ead222b79cfcea0da5fddf5b487c38c46e2d7c3b33a791
   Subject: Update IntelliJ IDEA to version 2024.2 (287266b8)
      Date: 2024-08-07 14:25:47 +0000

    Commit: 8ca75b8003330bb91f275cbb265bcb4548fb63c7cd7d95834d807b95177e0994
   Subject: Update IntelliJ IDEA to version 2024.1.5 (e3d8bba3)
      Date: 2024-08-06 13:31:27 +0000

    Commit: 8973b17380859fe70404a7b1d9a6145b077dba3f3d4f01ca57aa07b875c729d5
   Subject: Update IntelliJ IDEA to version 2024.1.4 (03ede7f4)
      Date: 2024-06-21 11:48:16 +0000

    Commit: ddcd195d21503b5726b276e10102649c77d45ebba53afbb95d4e554e92779e4a
   Subject: Update IntelliJ IDEA to version 2024.1.3 (554cc235)
      Date: 2024-06-10 16:56:44 +0000

    Commit: 35a9c3d2d2776e83d9738b7c3200925832c016ab4d15fe4b1e767af063fc2c01
   Subject: Update ideaIC.tar.gz to 2024.1.2 (#169) (a0c4d456)
      Date: 2024-05-23 14:48:36 +0000

    Commit: edceb1da4c1fbf671df1f1c1de41d708ad2eb910528c2517412d43fc2e05c40a
   Subject: Activate PulseAudio permission and enable access to the system's audio infrastructure (950a6025)
      Date: 2024-05-13 18:14:54 +0000

    Commit: bb01d1af6b191535b20fdc548e7c73c848b76d6b6f9e459d325aeda3d64a4e46
   Subject: Update ideaIC.tar.gz to 2024.1.1 (#167) (81ba62e7)
      Date: 2024-04-30 12:13:09 +0000

    Commit: 0f355b60823bcd19931f5a995e1d36b104285fe0f84585863fc51a216c8ccbbb
   Subject: Update rsync-3.2.7.tar.gz to 3.3.0 (f8d07d92)
      Date: 2024-04-07 20:39:46 +0000

    Commit: b41ec6b80f8d9d274896da58e848a820e4ddb300065d93c6b4853d728e00fa82
   Subject: Update IntelliJ IDEA Community to version 2024.1 (52d6eb66)
      Date: 2024-04-05 18:55:57 +0000
```
